// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.0
// source: proto/user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  company: string;
  password: string;
}

export interface UserDto {
  email: string;
  firstName: string;
  lastName: string;
  company: string;
  password: string;
}

export interface UserDetail {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  company: string;
}

export interface UserPreview {
  id: string;
  email: string;
}

export interface UserRegisterRequest {
  user: UserDto | undefined;
}

export interface UserRegisterResponse {
  id: string;
}

export interface UserLoginRequest {
  email: string;
  password: string;
}

export interface UserLoginResponse {
  token: string;
}

export interface UserDetailRequest {
  userId: string;
}

export interface UserDetailResponse {
  user: UserDetail | undefined;
}

export interface UserListResponse {
  users: UserPreview[];
}

export interface Empty {
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  register(request: UserRegisterRequest): Observable<UserRegisterResponse>;

  login(request: UserLoginRequest): Observable<UserLoginResponse>;

  userDetail(request: UserDetailRequest): Observable<UserDetailResponse>;

  listUsers(request: Empty): Observable<UserListResponse>;
}

export interface UserServiceController {
  register(
    request: UserRegisterRequest,
  ): Promise<UserRegisterResponse> | Observable<UserRegisterResponse> | UserRegisterResponse;

  login(request: UserLoginRequest): Promise<UserLoginResponse> | Observable<UserLoginResponse> | UserLoginResponse;

  userDetail(
    request: UserDetailRequest,
  ): Promise<UserDetailResponse> | Observable<UserDetailResponse> | UserDetailResponse;

  listUsers(request: Empty): Promise<UserListResponse> | Observable<UserListResponse> | UserListResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "userDetail", "listUsers"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
